#pragma once

#include <iostream>
#include <queue>

#define DEFAULT_IMAGE_WIDTH 4112
#define DEFAULT_IMAGE_HEIGHT 3008
#define RGB_DIFF_THRESHOLD 25
#define YUV_DIFF_SHADOW_THRESHOLD_Y 200
#define YUV_DIFF_SHADOW_THRESHOLD_UV 30
#define DENOISE_PIXEL_EDGE_SIZE 3
#define RGB_DIFF_DENOISE_THRESHOLD 50
#define MAX_DENOISE_COUNT 6
